### ISSUE TITLE
Intellisense, hovers etc for TS

### ISSUE THREAD

**Issue by kachurun** [Kal-Aster/vscode-riotjs#2]
Are these features implemented at all? I see a code that looks like it should do this, but it doesn't work for me. Moreover, I can see from the code that the path to the server is.js differs from where the file actually lies

**Comment by Kal-Aster** [comment]
I noticed it this morning. Before it worked, probably something broke when I decided to bundle the code in order to exclude the node_modules folder in the extension package. I'm on it!

Actually I'm talking only about autocomplete. I didn't even think about hover and code navigation, but I will.

**Comment by Kal-Aster** [comment]
Currently the autocompletion suggestions works only if I launch the extension in the development host in VSCode, so there's clearly a problem in the bundle.
However there is also a problem in the type resolution, the type checker does not resolve correctly the imported types.

Probably it's a problem with the module resolution? I'm digging into the issue

**Comment by Kal-Aster** [comment]
Latest commit fixes both the type resolution and the bundle.

Run `npm run package` and then install the extension from .vsix

I don't think I tested it enough, so let me know!
