### ISSUE TITLE
CSS Language Service

### ISSUE THREAD

**Issue by kachurun** [Kal-Aster/vscode-riotjs#8]
Please check this repo, it has great and simple example how to implement support of CSS autocompletion:

https://github.com/kachurun/vscode-extension-samples/tree/16a1c7c822f3d13bbc774123c9b7f3b697b9f1f1/lsp-embedded-language-service

**Comment by Kal-Aster** [comment]
Great!
I wrote the base for implementing the css autocompletion but never completed it 😅 Mainly because I’m using tailwindcss, so I don’t actually use the style tag, but I’ll add the support for css so this resource is surely valuable.
Thank you!

**Comment by Kal-Aster** [comment]
I'm closing this issue since it is just a reference. It was really helpful and probably it will be again, thank you again
